version: '3'
services:
  web0:
    image: setml
    ports:
      - "7000:7777"
    depends_on:
      - db
  web1:
    image: setml
    ports:
      - "7001:7777"
    depends_on:
      - db
  db:
    image: "postgres:10-alpine"
    environment:
      - POSTGRES_PASSWORD=at1234
      - POSTGRES_USER=atongen
      - POSTGRES_DB=setml_development
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/init.sql
