lib: [
  "_build/install/default/lib/setml/META" {"META"}
  "_build/install/default/lib/setml/opam" {"opam"}
]
bin: [
  "_build/install/default/bin/test_processes" {"test_processes"}
  "_build/install/default/bin/test_sequential" {"test_sequential"}
  "_build/install/default/bin/test_async" {"test_async"}
  "_build/install/default/bin/setml" {"setml"}
]
doc: [
  "_build/install/default/doc/setml/README.md"
]
